### ISSUE TITLE
No module named 'street_gaussians_ns.cameras'

### ISSUE THREAD

**Issue by sonnefred** [LightwheelAI/street-gaussians-ns#1]
Hi, thanks for reproducing the paper and sharing the work. I want to have a try on Waymo dataset, but I got the following error. Is there anything I missed during installing the environment? Thanks.
![jietu-1716451366107](https://github.com/LightwheelAI/street-gaussians-ns/assets/66628395/30248ef5-7b55-438a-90af-f00c570fab70)

**Comment by LightwheelAI** [comment]
Thanks for the issue, and I'm very sorry, the bug came from our process of cleaning up the code. I've updated the code to solve this issue, you can try the latest code!

**Comment by sonnefred** [comment]
> Thanks for the issue, and I'm very sorry, the bug came from our process of cleaning up the code. I've updated the code to solve this issue, you can try the latest code!

Thanks for the reply, and the problem has been solved, but I met this error, I'm not sure what caused this. Thanks.
![jietu-1716466063698](https://github.com/LightwheelAI/street-gaussians-ns/assets/66628395/79d7bb18-7a4c-42da-b1ed-9f78f83d5656)

**Comment by merriaux** [comment]
Hi, many thanks for the sharing 
It looks like there is another small error in pcd2colmap_points3D.py shell script call:
![image](https://github.com/LightwheelAI/street-gaussians-ns/assets/16850602/e9725c00-7383-4081-b072-a5fa0db63145)

I tried to remove --output_path arg, but I don't have the file: colmap/sparse/lidar/points3D.txt in my dataset folder after running colmap.
thanks

**Comment by zwlvd** [comment]
Thank you for your advice @merriaux 
I follow your way to change the code , while I still meet the same error. 
Do you succeed to run the segs_generate.sh?

**Comment by zwlvd** [comment]
@merriaux Thank you very much. It is useful.

**Comment by merriaux** [comment]
I reach to start a training but it crashed at iteration 3990:
![image](https://github.com/LightwheelAI/street-gaussians-ns/assets/16850602/22cacb54-2cdc-4df5-940c-699e1e66ab7c)

```
Exception in thread Thread-17:                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                   
  File "/data/anaconda3/envs/street-gaussians-ns/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                          
    self.run()                                                                                                                                                                                       
  File "/data/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/viewer/render_state_machine.py", line 224, in run                                                            
    outputs = self._render_img(action.camera_state)                                                                                                                                                  
  File "/data/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/viewer/render_state_machine.py", line 168, in _render_img                                                    
    outputs = self.viewer.get_model().get_outputs_for_camera(camera, obb_box=obb)                                                                                                                    
  File "/data/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context                                                              
    return func(*args, **kwargs)                                                                                                                                                                     
  File "/data/workspace/pierre.merriaux/street-gaussians-ns/street_gaussians_ns/sgn_splatfacto.py", line 1106, in get_outputs_for_camera                                                             
    outs = self.get_outputs(camera.to(self.device))                                               
  File "/data/workspace/pierre.merriaux/street-gaussians-ns/street_gaussians_ns/sgn_splatfacto_scene_graph.py", line 363, in get_outputs                                                             
    out = super().get_outputs(camera)                                                             
  File "/data/workspace/pierre.merriaux/street-gaussians-ns/street_gaussians_ns/sgn_splatfacto.py", line 858, in get_outputs                                                                         
    colors_crop = torch.cat((features_dc_crop, features_rest_crop), dim=1)                        
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 298587 but got size 437860 for tensor number 1 in the list.
```
In dataset preparation, there few path are wrong. And I am not sure of my colmap processing.
thanks

**Comment by LightwheelAI** [comment]
@merriaux
Thank you very much for catching the problem in our script!  I made some mistakes in the ```points_cloud_generate.sh``` and ```run_colmap.sh```. In ```scripts/pythons/pcd2colmap_points3D.py```, output path defaults to ```colmap/sparse/lidar/points3D.txt```, so we need create a folder ```colmap/sparse/lidar``` and use it as the ```--src1``` of ```scripts/pythons/colmap_pts_combine.py```.
About the ```run_colmap.sh```, ```--input_path1``` of ```model_comparer``` should be ```$DATASET_PATH/colmap/sparse/not_align/0``` corresponding to the ```--output_path``` of ```mapper```.
The ```point_triangulator``` step is not necessary if ```mapper``` successed. ```--output_path``` of ```point_triangulator``` will create a SfM points file and may cover the result of ```mapper```.

I fixed the bugs in the bash file and updated it to the repository based on your feedback！

**Comment by LightwheelAI** [comment]
@merriaux
Regarding the problem you had during your training, I'm sorry that I can't reproduce the problem. Would you be so kind to make more attempts to get more information?

![37D5FE322DA49D6EE7B394D2DCB71081](https://github.com/LightwheelAI/street-gaussians-ns/assets/159144751/e2e5d6fe-04e0-4853-98c2-ccf54ba71b90)

**Comment by merriaux** [comment]
thanks for all @LightwheelAI,
Let me first retry with the right data processing pipeline, and see if the training will be better

**Comment by blackmrb** [comment]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 995/995 [00:50<00:00, 19.82it/s]
Traceback (most recent call last):
  File "scripts/pythons/colmap_pts_combine.py", line 27, in <module>
    colmap_points2 = read(args.src2)
  File "scripts/pythons/colmap_pts_combine.py", line 17, in read
    return colmap_utils.read_points3D_binary(path)
  File "/mnt/data/code/nerfstudio/nerfstudio/data/utils/colmap_parsing_utils.py", line 344, in read_points3D_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/root/code/street-gaussians-ns/data/waymo/processed/training/1191788760630624072_3880_000_3900_000/colmap/sparse/0/points3D.bin'

I have the same problem.

> hi @LightwheelAI, There is something I don't catch in data preparation:
> 
> ```
> colmap model_comparer \
>     --input_path1 $DATASET_PATH/colmap/sparse/not_align/0 \
>     --input_path2 $DATASET_PATH/colmap/sparse/origin \
>     --output_path $DATASET_PATH/colmap/sparse/0 \
>     --alignment_error proj_center
> ```
> 
> I was not enable to find document about `model_comparer` (I looked directly in the colmap code), but at the end it just compares 2 models, and give us two text files (errors_summary.txt, and errors.csv). Next step of data processing crashes because we are looking for a colmap model in `sparse/0`. Do you forget to call `model_aligner` ?. Because from my understanding of data processing, we want to "merge" colmap mapper point cloud in waymo point cloud referential ? or is it waymo point cloud in colmap mapper point cloud referential ?
> 
> If I am right, what the data processing is supposed to do:
> 
> * camera pose and intrinsic parameter from waymo
> * background point cloud: waymo front lidar (colorized from camera, and remove point in objects box) + colmap mapper point cloud (but need alignment because mapper)
> * objects: Lidar TOP point in objects boxes, colorized by cameras
> 
> Could you please help to understand ? thanks

**Comment by LightwheelAI** [comment]
@merriaux
Thanks for trying, your understanding is spot on! I'm very sorry, I neglected to mention that we made additional changes to colmap to make it output ```points3D.bin```. There are fewer parts that need to be modified, you can refer to the way we modified it as follow and then recompile your colmap.
best
![20240527-110159](https://github.com/LightwheelAI/street-gaussians-ns/assets/159144751/a1cae577-8636-4986-828b-79d487ea08be)

**Comment by merriaux** [comment]
Hi @LightwheelAI, 
Thanks for your message. 
- Could you please confirm that you are merging colmap point cloud in waymo point cloud (or the inverse) ?  
- So line 571, of colmap model.cc , I can transform directly reconstuction1 (mapper result) with transform rec2_from_rec1, so code should looks like:
```
  reconstruction1.Transform(rec2_from_rec1)
  reconstruction1.write(output_path)
```
for sequence 10588771936253546636_2300_000_2320_000, the result of model_ comparer is:
```
I0524 21:16:12.028003     1 model.cc:565] Computed alignment transform:
-7.33663  1.63006 -10.2083 -163.678
 6.14792 -9.37555 -5.91557  244.389
-8.31077 -8.37459  4.63565  4.07124
I0524 21:16:12.029619     1 misc.cc:205] 
Image alignment error summary
-----------------------------

Rotation errors (degrees)
Min:    43.9831
Max:    95.4597
Mean:   54.4792
Median: 48.8893
P90:    85.0368
P99:    93.6138

Projection center errors
Min:    0.00893002
Max:    83.8678
Mean:   8.66299
Median: 1.58935
P90:    31.7972
P99:    74.711
```

I quite surprise of the matrix found: 
```
-7.33663  1.63006 -10.2083 -163.678
 6.14792 -9.37555 -5.91557  244.389
-8.31077 -8.37459  4.63565  4.07124
```
do you it make sens ?
thanks

**Comment by merriaux** [comment]
It looks like there is a typo in `scripts/shells/data_process.sh`
-sh scripts/shells/extract_object_pts.py $root
need to be replaced by
+sh scripts/shells/object_pts_generate.sh $root

I have an issue now with the dataparser, camera_id goes to 995 different cameras in place of 5. `cam_id_to_camera = colmap_utils.read_cameras_binary(recon_dir / "cameras.bin")` return 995 entries, so after datamanager fail. It looks like the mapper don't keep camera id one per image folder.
- do we want to use original waymo camera intrinsics parameters and poses ? in this case I can copy images.txt and cameras.txt from `origin` folder to `sparse/0`
- or use the extrinsic poses from mapper "refinement". 
thanks

**Comment by merriaux** [comment]
Hi @LightwheelAI, thanks for your answer.
At the end in the in the training process, do you use poses and intrinsics from waymo dataset, or an optimized poses and intrinsics from sfm/colmap optimization preprocess ?

**Comment by LightwheelAI** [comment]
Thanks for your interest in our work! It depends, we use the optimized parameters when colmap runs successfully, otherwise we use waymo's original parameters:)

**Comment by merriaux** [comment]
thanks

**Comment by lziiid** [comment]
> It looks like there is a typo in `scripts/shells/data_process.sh` -sh scripts/shells/extract_object_pts.py $root need to be replaced by +sh scripts/shells/object_pts_generate.sh $root
> 
> I have an issue now with the dataparser, camera_id goes to 995 different cameras in place of 5. `cam_id_to_camera = colmap_utils.read_cameras_binary(recon_dir / "cameras.bin")` return 995 entries, so after datamanager fail. It looks like the mapper don't keep camera id one per image folder.
> 
> * do we want to use original waymo camera intrinsics parameters and poses ? in this case I can copy images.txt and cameras.txt from `origin` folder to `sparse/0`
> * or use the extrinsic poses from mapper "refinement", probably in this case `features_extractor` need to be launch with `--ImageReader.single_camera_per_folder 1.`
>   thanks

Hi, I met the same problem as you. Could you kindly share how you solve it?

**Comment by leledewanan** [comment]
> @merriaux Thanks for trying, your understanding is spot on! I'm very sorry, I neglected to mention that we made additional changes to colmap to make it output `points3D.bin`. There are fewer parts that need to be modified, you can refer to the way we modified it as follow and then recompile your colmap. best ![20240527-110159](https://private-user-images.githubusercontent.com/159144751/333944482-a1cae577-8636-4986-828b-79d487ea08be.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzI3MDYsIm5iZiI6MTcyNDgzMjQwNiwicGF0aCI6Ii8xNTkxNDQ3NTEvMzMzOTQ0NDgyLWExY2FlNTc3LTg2MzYtNDk4Ni04MjhiLTc5ZDQ4N2VhMDhiZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDgwNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhhMTFjZGE1N2QyZGRlZWU3Y2NlYWNmMzE5N2Y2NmFmMmIxMmMyOGRlYjNhZDE5NzkxODQwMzIyY2RiMGU5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wi9m9qETz0Q4C8rrgBoIzR4q6ffop496eZW_2oOvfkU)

Hello, @LightwheelAI ,thank you for your help. When I processed waymo data, an error occurred:



Traceback (most recent call last):

File "scripts/pythons/colmap_pts_combine.py", line 27, in <module>

colmap_points2 = read(args.src2)

File "scripts/pythons/colmap_pts_combine.py", line 17, in read

return colmap_utils.read_points3D_binary(path)

File "/home/... / anaconda3 / envs/street - gaussians - ns/lib/python3.8 / site - packages/nerfstudio/data/utils/colmap_parsing_utils py ", line 344, in read_points3D_binary

with open(path_to_model_file, "rb") as fid:

FileNotFoundError: [Errno 2] No such file or directory: '/home/... /output_waymo_data/training/10072140764565668044_4060_000_4080_000/colmap/sparse/0/points3D.bin'




So I modified /src/colmap/exe/model.cc according to the picture you provided, and a new problem appeared when recompiling colmap:



/home/... /colmap/src/colmap/exe/model.cc: In function ‘int colmap::RunModelComparer(int, char**)’:

/home/... /colmap/src/colmap/exe/model.cc:521:31: error: ‘new_from_old_world’ was not declared in this scope

521 |     reconstruction1.Transform(new_from_old_world);

| ^ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

/home/... /colmap/src/colmap/exe/model.cc: In function ‘int colmap::RunModelComparer(int, char**)’:

/home/... /colmap/src/colmap/exe/model.cc:521:31: error: ‘new_from_old_world’ was not declared in this scope

521 |     reconstruction1.Transform(new_from_old_world);



| ^ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~



Could you please help to understand the following and provide some suggestions? Thank you very much

**Comment by tcytan** [comment]
@leledewanan 
I meet the error as yours,do you solve it?

**Comment by Ediolot** [comment]
@leledewanan @tcytan I suspect the solution is using the `rec2_from_rec1` variable instead of `new_from_old_world`. I guess they have their own colmap fork that uses a version earlier than this [commit](https://github.com/colmap/colmap/commit/faee9ea5deb746e328d9c6db170e0a39140b6bcc) where the `new_from_old_world` variable was still there
