### ISSUE TITLE
Errors in mask2former during data preprocessing.

### ISSUE THREAD

**Issue by markinruc** [LightwheelAI/street-gaussians-ns#10]
Hi, @LightwheelAI , when I ran data_process.sh, I encountered an error with segs_generate.sh.

`(street-gaussians-ns) @icess:/mnt/sdb/public/data/street-gaussians-ns$ bash scripts/shells/segs_generate.sh data/processed_waymo/training/10448102132863604198_472_000_492_000/

[06/01 13:18:22 detectron2]: Arguments: Namespace(base_dir='#####/Nuscenes/sweeps/', confidence_threshold=0.5, config_file='dependencies/Mask2Former/configs/mapillary-vistas/semantic-
segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_300k.yaml', opts=['MODEL.WEIGHTS', 'dependencies/Mask2Former/models/model_final_90ee2d.pkl'], output=None, 
root_path='data/processed_waymo/training/10448102132863604198_472_000_492_000/', save_dir='#####/KittiOdom/sequences', video_input=None, webcam=False)

WARNING [06/01 13:18:22 fvcore.common.config]: Loading config dependencies/Mask2Former/configs/mapillary-vistas/semantic-segmentation/swin/../Base-MapillaryVistas-SemanticSegmentation.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

Traceback (most recent call last):

  File "dependencies/Mask2Former/segs_generate.py", line 234, in <module>
    demo = VisualizationDemo(cfg)

  File "/mnt/sdb/public/data/ws/street-gaussians-ns/dependencies/Mask2Former/demo/predictor.py", line 37, in __init__
    self.predictor = DefaultPredictor(cfg)

  File "/mnt/sdb/public/data/ws/street-gaussians-ns/dependencies/detectron2/detectron2/engine/defaults.py", line 282, in __init__
    self.model = build_model(self.cfg)

  File "/mnt/sdb/public/data/ws/street-gaussians-ns/dependencies/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)

  File "/home/ws/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'MaskFormer' found in 'META_ARCH' registry!"`

I have completed the subsequent experiments using the data you provided. However, I still wish to resolve the data preprocessing issue. Do I need to perform any additional operations on detectron2?

**Comment by LightwheelAI** [comment]
Hi，thanks for your trying! I think this could be helpful!
https://github.com/LightwheelAI/street-gaussians-ns/issues/1#issuecomment-2127463228
