### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by 13678066760** [LightwheelAI/street-gaussians-ns#33]
Hi, nice work! When I was in traing process, I came across a problem with dockerpycreds, here's the log. :
Traceback (most recent call last):
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/__main__.py", line 1, in <module>
    from wandb.cli import cli
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/cli/cli.py", line 2151, in <module>
    default=find_executable("nvidia-docker") is not None,
  File "/home/adsec/.local/lib/python3.8/site-packages/dockerpycreds/utils.py", line 12, in find_executable
    return distutils.spawn.find_executable(executable, path)
AttributeError: module 'distutils' has no attribute 'spawn'
Traceback (most recent call last):
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 204, in setup
    writer.setup_event_writer(
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/decorators.py", line 82, in wrapper
    ret = func(*args, **kwargs)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/writer.py", line 223, in setup_event_writer
    curr_writer = WandbWriter(log_dir=log_dir, experiment_name=experiment_name, project_name=project_name)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/writer.py", line 310, in __init__
    wandb.init(
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    wandb._sentry.reraise(e)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1180, in init
    wi.setup(kwargs)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 189, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 325, in setup
    ret = _setup(settings=settings)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 318, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 283, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 141, in __init__
    self._service.start()
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 253, in start
    self._launch_server()
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 247, in _launch_server
    _sentry.reraise(e)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 245, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 109, in _wait_for_ports
    raise ServiceStartProcessError(
wandb.sdk.service.service.ServiceStartProcessError: The wandb service process exited with 1. Ensure that `sys.executable` is a valid python interpreter. You can override it with the `_executable` setting or with the `WANDB__EXECUTABLE` environment variable.
{'command': ['/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/python', '-m', 'wandb', 'service', '--debug', '--port-filename', '/tmp/tmppbt0yuji/port-1346013.txt', '--pid', '1346013', '--serve-sock'], 'sys_executable': '/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/python', 'which_python': '/ho(stree(st(street-g(stree(stree(stree(stree(st(st(st(street-gaussians-ns)

**Comment by justeWang** [comment]
> Hi, nice work! When I was in traing process, I came across a problem with dockerpycreds, here's the log. : Traceback (most recent call last): File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/**main**.py", line 1, in from wandb.cli import cli File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/cli/cli.py", line 2151, in default=find_executable("nvidia-docker") is not None, File "/home/adsec/.local/lib/python3.8/site-packages/dockerpycreds/utils.py", line 12, in find_executable return distutils.spawn.find_executable(executable, path) AttributeError: module 'distutils' has no attribute 'spawn' Traceback (most recent call last): File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in sys.exit(entrypoint()) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main launch( File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop trainer.setup() File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 204, in setup writer.setup_event_writer( File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/decorators.py", line 82, in wrapper ret = func(*args, **kwargs) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/writer.py", line 223, in setup_event_writer curr_writer = WandbWriter(log_dir=log_dir, experiment_name=experiment_name, project_name=project_name) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/utils/writer.py", line 310, in **init** wandb.init( File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init wandb._sentry.reraise(e) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise raise exc.with_traceback(sys.exc_info()[2]) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1180, in init wi.setup(kwargs) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 189, in setup self._wl = wandb_setup.setup(settings=setup_settings) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 325, in setup ret = _setup(settings=settings) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 318, in _setup wl = _WandbSetup(settings=settings) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 303, in **init** _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 114, in **init** self._setup() File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup self._setup_manager() File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 283, in _setup_manager self._manager = wandb_manager._Manager(settings=self._settings) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 141, in **init** self._service.start() File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 253, in start self._launch_server() File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 247, in _launch_server _sentry.reraise(e) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise raise exc.with_traceback(sys.exc_info()[2]) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 245, in _launch_server self._wait_for_ports(fname, proc=internal_proc) File "/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 109, in _wait_for_ports raise ServiceStartProcessError( wandb.sdk.service.service.ServiceStartProcessError: The wandb service process exited with 1. Ensure that `sys.executable` is a valid python interpreter. You can override it with the `_executable` setting or with the `WANDB__EXECUTABLE` environment variable. {'command': ['/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/python', '-m', 'wandb', 'service', '--debug', '--port-filename', '/tmp/tmppbt0yuji/port-1346013.txt', '--pid', '1346013', '--serve-sock'], 'sys_executable': '/home/adsec/anaconda/anaconda3/envs/street-gaussians-ns/bin/python', 'which_python': '/ho(stree(st(street-g(stree(stree(stree(stree(st(st(st(street-gaussians-ns)

Hello, I also encountered the same problem, may I ask you to solve it?
