### ISSUE TITLE
preprocessed datasets are missing file points3D_withlidar.txt

### ISSUE THREAD

**Issue by MarcusVH98** [LightwheelAI/street-gaussians-ns#53]
in `waymo_8398516118967750070_3958_000_3978_000/8398516118967750070_3958_000_3978_000/colmap/sparse/0` there is no `points3D_withlidar.txt` file. The same is true for the three other preprocessed datasets.

This results in the following traceback when trying to train with `bash scripts/shells/train.sh waymo_8398516118967750070_3958_000_3978_000/8398516118967750070_3958_000_3978_000 0`:
```
Traceback (most recent call last):
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 149, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 254, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/media/marcus/data/marcus_data/street-gaussians-ns/street_gaussians_ns/data/sgn_datamanager.py", line 100, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/marcus/miniconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/media/marcus/data/marcus_data/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 444, in _generate_dataparser_outputs
    metadata.update(self._load_3D_points(colmap_path, transform_matrix, scale_factor))
  File "/media/marcus/data/marcus_data/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 478, in _load_3D_points
    assert points_filepath.exists()
AssertionError
```

I got past the error by editing `scripts/shells/train.sh` argument `init_points_filename` from `points3D_withlidar.txt` to `points3D.bin`, but not sure if that file has lidar information.

Not sure if my change will work, because I get another error `TypeError: project_gaussians() missing 1 required positional argument: 'tile_bounds'`, see issue #52

**Comment by mingzhuzhang1** [comment]
Hello, I have encountered the same issue. Have you managed to solve it? How should I go about resolving this problem?
TypeError: project_gaussians() missing 1 required positional argument: 'tile_bounds'
